Completed

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -13,21 +13,23 @@ jobs:
         env:
           GH_TOKEN: ${{ github.token }}
         run: |
-          bash compile.sh || {
-            echo "Compilation failed."
-            exit 1
-          }
+          for hypervisor in virtualbox vmware; do
+            bash compile.sh "$hypervisor" || {
+              echo "Compilation failed."
+              exit 1
+            }
 
-          VM_CLI_VERSION="$(awk -F= '/VM_CLI_VERSION/ {gsub(/"/, "", $2); print $2; exit}' dist/vm-cli)"
-          if [ -z "$VM_CLI_VERSION" ]; then
-            echo "Version not found in vm-cli file."
-            exit 1
-          fi
+            VM_CLI_VERSION="$(awk -F= '/VM_CLI_VERSION/ {gsub(/"/, "", $2); print $2; exit}' dist/$hypervisor/vm-cli)"
+            if [ -z "$VM_CLI_VERSION" ]; then
+              echo "Version not found in vm-cli file."
+              exit 1
+            fi
 
-          tar -czf vm-cli.tar.gz -C dist vm-cli || {
-            echo "Failed to create tar.gz file."
-            exit 2
-          }
+            tar -czf vm-cli.$hypervisor.tar.gz -C dist vm-cli/$hypervisor || {
+              echo "Failed to create tar.gz file."
+              exit 2
+            }
+          done
 
           # Delete all previous releases.
           while read -r tag; do
@@ -36,4 +38,4 @@ jobs:
 
           # Create a new release.
           compiled_at="$(date -u +'%Y-%m-%d %H:%M:%S %Z')"
-          gh release create "v$VM_CLI_VERSION" vm-cli.tar.gz --title "Release v$VM_CLI_VERSION" --notes "Latest version compiled at $compiled_at" --latest
+          gh release create "v$VM_CLI_VERSION" vm-cli.virtualbox.tar.gz vm-cli.vmware.tar.gz--title "Release v$VM_CLI_VERSION" --notes "Latest version compiled at $compiled_at" --latest
